// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQxiO1fg_tE5DcyRJWm99CrSVVNxhDqBo',
    appId: '1:301822310762:android:bc200a88a8e8e48dbfcd13',
    messagingSenderId: '301822310762',
    projectId: 'flutterip-1ddd8',
    databaseURL: 'https://flutterip-1ddd8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterip-1ddd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_xy6_cicEqozQvfDBmfJ1H0fQa3o3TD8',
    appId: '1:301822310762:ios:c762af0ffb7bc0abbfcd13',
    messagingSenderId: '301822310762',
    projectId: 'flutterip-1ddd8',
    databaseURL: 'https://flutterip-1ddd8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterip-1ddd8.appspot.com',
    iosClientId: '301822310762-g7s2p411nqg4bocqkrnkip7kjbesi4u8.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled4',
  );
}
